services:
  mongo-database:
    container_name: mongo-database
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=bmw_database

volumes:
  mongodb_data: